[package]
name = "my_rust_project"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
egg-mode = "0.16.1"
rig-core = "0.5.0"
